### File Handling -- JSON

In [6]:
"""
"orders": [
    {
      "order_id": 1001,
      "customer": {
        "name": "Alice Johnson",
        "city": "New York"
      },
      "items": [
        {"product": "Laptop", "price": 1200, "quantity": 1},
        {"product": "Mouse", "price": 25, "quantity": 2}
      ],
      "status": "shipped"
    },
    {
      "order_id": 1002,
      "customer": {
        "name": "Bob Smith",
        "city": "Chicago"
      },
      "items": [
        {"product": "Phone", "price": 800, "quantity": 1},
        {"product": "Headphones", "price": 150, "quantity": 1}
      ],
      "status": "processing"
    },
    {
      "order_id": 1003,
      "customer": {
        "name": "Carla Gomez",
        "city": "San Francisco"
      },
      "items": [
        {"product": "Tablet", "price": 600, "quantity": 1}
      ],
      "status": "delivered"
    }
  ]
}"""

'\n"orders": [\n    {\n      "order_id": 1001,\n      "customer": {\n        "name": "Alice Johnson",\n        "city": "New York"\n      },\n      "items": [\n        {"product": "Laptop", "price": 1200, "quantity": 1},\n        {"product": "Mouse", "price": 25, "quantity": 2}\n      ],\n      "status": "shipped"\n    },\n    {\n      "order_id": 1002,\n      "customer": {\n        "name": "Bob Smith",\n        "city": "Chicago"\n      },\n      "items": [\n        {"product": "Phone", "price": 800, "quantity": 1},\n        {"product": "Headphones", "price": 150, "quantity": 1}\n      ],\n      "status": "processing"\n    },\n    {\n      "order_id": 1003,\n      "customer": {\n        "name": "Carla Gomez",\n        "city": "San Francisco"\n      },\n      "items": [\n        {"product": "Tablet", "price": 600, "quantity": 1}\n      ],\n      "status": "delivered"\n    }\n  ]\n}'

In [18]:
import json
import pandas as pd

#### Reading the JSON data from a JSON file

In [10]:
with open("1.a. JSON dumps/data.json") as file:
    data = json.load(file)
print(data)

{'orders': [{'order_id': 1001, 'customer': {'name': 'Alice Johnson', 'city': 'New York'}, 'items': [{'product': 'Laptop', 'price': 1200, 'quantity': 1}, {'product': 'Mouse', 'price': 25, 'quantity': 2}], 'status': 'shipped'}, {'order_id': 1002, 'customer': {'name': 'Bob Smith', 'city': 'Chicago'}, 'items': [{'product': 'Phone', 'price': 800, 'quantity': 1}, {'product': 'Headphones', 'price': 150, 'quantity': 1}], 'status': 'processing'}, {'order_id': 1003, 'customer': {'name': 'Carla Gomez', 'city': 'San Francisco'}, 'items': [{'product': 'Tablet', 'price': 600, 'quantity': 1}], 'status': 'delivered'}]}

#### Writing JSON data into a `.JSON` file

In [15]:
with open("data.json",'w') as file:
    json.dump(data,file)

#### Use indent parameter in json dump to make the data more readable

In [16]:
with open("data.json",'w') as file:
    json.dump(data,file, indent = 4)

print(data)

{'orders': [{'order_id': 1001, 'customer': {'name': 'Alice Johnson', 'city': 'New York'}, 'items': [{'product': 'Laptop', 'price': 1200, 'quantity': 1}, {'product': 'Mouse', 'price': 25, 'quantity': 2}], 'status': 'shipped'}, {'order_id': 1002, 'customer': {'name': 'Bob Smith', 'city': 'Chicago'}, 'items': [{'product': 'Phone', 'price': 800, 'quantity': 1}, {'product': 'Headphones', 'price': 150, 'quantity': 1}], 'status': 'processing'}, {'order_id': 1003, 'customer': {'name': 'Carla Gomez', 'city': 'San Francisco'}, 'items': [{'product': 'Tablet', 'price': 600, 'quantity': 1}], 'status': 'delivered'}]}

#### Since we have the data in a variable how to put it in a more readable format?

In [17]:
orders = data["orders"]

for order in orders:
    print("Order ID:", order["order_id"])
    print("Customer:", order["customer"]["name"])

    total = 0
    for item in order["items"]:
        total += item["price"] * item["quantity"]

    print("Total Price:", total)
    print("Status:", order["status"])
    print("-" * 40)

Order ID: 1001
Customer: Alice Johnson
Total Price: 1250
Status: shipped
----------------------------------------
Order ID: 1002
Customer: Bob Smith
Total Price: 950
Status: processing
----------------------------------------
Order ID: 1003
Customer: Carla Gomez
Total Price: 600
Status: delivered
----------------------------------------

#### How do we put the data in a tabular format? --> `pd.json_normalize`

In [24]:
pd.json_normalize(data['orders'],record_path="items" ,\
                  meta = [
                            'order_id', \
                            ["customer","name"], ["customer","city"],\
#                             ["items","product"], ["items","price"], ["items","quantity"],\
                            ["status"]
                         ]

                 )

,product,price,quantity,order_id,customer.name,customer.city,status
0,Laptop,1200,1,1001,Alice Johnson,New York,shipped
1,Mouse,25,2,1001,Alice Johnson,New York,shipped
2,Phone,800,1,1002,Bob Smith,Chicago,processing
3,Headphones,150,1,1002,Bob Smith,Chicago,processing
4,Tablet,600,1,1003,Carla Gomez,San Francisco,delivered

In [23]:
pd.json_normalize(
    data["orders"],
    record_path="items",
    meta=["order_id", ["customer", "name"], ["customer", "city"], "status"]
)

,product,price,quantity,order_id,customer.name,customer.city,status
0,Laptop,1200,1,1001,Alice Johnson,New York,shipped
1,Mouse,25,2,1001,Alice Johnson,New York,shipped
2,Phone,800,1,1002,Bob Smith,Chicago,processing
3,Headphones,150,1,1002,Bob Smith,Chicago,processing
4,Tablet,600,1,1003,Carla Gomez,San Francisco,delivered

Here is that concept formatted in clean, scannable Markdown:

---
JSON dumps get truly "complex" when they contain lists of objects *inside* the main objects. To flatten these, you need to explicitly tell `json_normalize()` two things:

* **What to unpack:** The specific nested list you want to expand (using the `record_path` argument).
* **What to keep:** The parent fields you want to retain alongside that unpacked data (using the `meta` argument).

### In-Memory Databases (SQL Lite)

In [ ]:
import sqlite3 
import pandas as pd